services:
  app:
    build: .
    restart: "always"
    ports:
      - "7501:8501"
    volumes:
      - storage:/app/data:rw
    env_file:
      - ./gcs.env
    environment:
      - VIRTUAL_HOST=app.solonumeros.com.ar
        #- VIRTUAL_PORT=2000

  calculator:
    build: ../gv_xml/
    volumes:
      - storage:/data/share:rw
    ports:
      - "3000:3000"
    env_file:
      - ./gcs.env
      - ../gv_xml/docker.env
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 7000:8080
    volumes:
      - storage:/data
      - /home/goodvibes/gv_xml_ui/filebrowser/config:/config:rw
    environment:
      - FB_BASEURL=/filebrowser
      - VIRTUAL_HOST=filebrowser.localhost 
    restart: always

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      - VIRTUAL_HOST=db.localhost  
    deploy:
      replicas: 0 
volumes:
  storage:
